deploy:
    edge:
        branch: sf-docker
    password: $DOCKER_PASSWORD
    provider: docker
    target: $DOCKER_TAG
    username: $DOCKER_USERNAME
language: minimal
script: docker build -t $DOCKER_TAG .
